# Notebook 1 – Introduction to NumPy

## 1. What is NumPy?

### Definition
NumPy (Numerical Python) is a Python library used for fast numerical calculations and multidimensional arrays.

### Real-Life Example
A shop can store daily sales as numbers and calculate them together.

### AI/ML Example
In AI/ML, NumPy is used to store and process numerical datasets, model inputs, and weights. It helps perform fast mathematical operations on large amounts of data. Many ML libraries also work closely with NumPy arrays.

### Explanation
NumPy provides the ndarray object for efficient numerical operations. It can process many values together instead of handling each value separately. This makes numerical computation simple and fast.

### Python Implementation


In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


## 2. Why NumPy?

### Definition
NumPy provides fast, memory-efficient array operations and built-in mathematical functions.

### Real-Life Example
Marks of many students can be processed together to calculate averages and totals.

### AI/ML Example
In AI/ML, we repeatedly perform calculations on large numerical datasets. NumPy performs these operations efficiently using arrays and vectorized calculations. This makes data preparation and model computations faster.

### Explanation
NumPy is faster and more memory-efficient than using normal Python lists for many numerical tasks. Vectorized operations work on entire arrays without writing many loops. It also provides many useful mathematical functions.

### Python Implementation


In [3]:
import numpy as np
marks=np.array([65,72,80,85,90])
print('Average:',np.mean(marks))
print('Highest:',np.max(marks))

Average: 78.4
Highest: 90


## 3. NumPy Arrays (ndarray)

### Definition
A NumPy array, called ndarray, is a collection of elements stored in one or more dimensions.

### Real-Life Example
Daily temperatures can be stored in one NumPy array.

### AI/ML Example
In AI/ML, features such as age, salary, and experience can be stored in ndarray format. Rows can represent samples and columns can represent features. Models can then process this numerical data efficiently.

### Explanation
ndarray is the main data structure in NumPy. It can store data in one or multiple dimensions and supports fast mathematical operations. All elements usually have the same data type.

### Python Implementation


In [5]:
import numpy as np
arr=np.array([12,24,36,48])
print(arr)
print(type(arr))

[12 24 36 48]
<class 'numpy.ndarray'>


## 4. Creating Arrays

### Definition
Creating arrays means converting data into ndarray objects or generating arrays with NumPy functions.

### Real-Life Example
Daily product sales can be stored as an array.

### AI/ML Example
In AI/ML, training data can be converted into NumPy arrays before preprocessing or model training. We can also create arrays filled with zeros or ones for initialization. This is useful in many numerical and ML operations.

### Explanation
Arrays can be created from Python lists using np.array(). NumPy also provides functions such as np.zeros(), np.ones(), and np.arange(). These functions make array creation quick and flexible.

### Python Implementation


In [7]:
import numpy as np
print(np.array([5,10,15,20]))
print(np.zeros(4))
print(np.ones(4))
print(np.arange(1,6))

[ 5 10 15 20]
[0. 0. 0. 0.]
[1. 1. 1. 1.]
[1 2 3 4 5]


## 5. Dimensions

### Definition
Dimensions describe the number of axes in a NumPy array.

### Real-Life Example
One row of marks is 1D, while marks for multiple students and subjects can be 2D.

### AI/ML Example
In AI/ML, a 1D array can represent one feature or one sample. A 2D array commonly represents multiple samples and features. Higher-dimensional arrays are also common for images and deep-learning data.

### Explanation
Dimensions describe how an array is organized. The ndim attribute tells us how many dimensions an array contains. Understanding dimensions helps us prepare data in the correct format.

### Python Implementation


In [9]:
import numpy as np
a=np.array([10,20,30])
b=np.array([[10,20,30],[40,50,60]])
print(a.ndim)
print(b.ndim)

1
2


## 6. Shape

### Definition
Shape tells the number of elements along each dimension of an array.

### Real-Life Example
A table with 3 students and 2 subject marks has 3 rows and 2 columns.

### AI/ML Example
In AI/ML, shape helps verify the number of samples and features in a dataset. For example, (100, 4) can mean 100 samples with 4 features each. Correct shape is important before giving data to a model.

### Explanation
Shape describes the length of each dimension in an array. For 2D data, it is commonly shown as (rows, columns). We can check it using the shape attribute.

### Python Implementation


In [11]:
import numpy as np
arr=np.array([[10,20],[30,40],[50,60]])
print('Shape:',arr.shape)

Shape: (3, 2)


## 7. Size

### Definition
Size gives the total number of elements in a NumPy array.

### Real-Life Example
A table with 3 rows and 4 columns contains 12 values.

### AI/ML Example
In AI/ML, size can be used to check the total number of numerical values in an array. It is useful when understanding the amount of data being processed. It works for arrays of any dimension.

### Explanation
The size attribute returns the total number of elements in an array. For example, a 2 × 3 array has a size of 6. It counts all elements across every dimension.

### Python Implementation


In [13]:
import numpy as np
arr=np.array([[2,4,6],[8,10,12]])
print('Size:',arr.size)

Size: 6


## 8. Data Types

### Definition
A data type defines the type of values stored in an array, such as integer, float, or boolean.

### Real-Life Example
Age can be stored as an integer while height can be stored as a decimal.

### AI/ML Example
In AI/ML, correct data types are important because models perform mathematical calculations on numerical features. For example, integer data may sometimes need to be converted to float. Choosing suitable types can also help memory usage.

### Explanation
The dtype attribute shows the type of data stored in an array. NumPy supports integers, floats, booleans, and other types. astype() can be used when we need to convert the data type.

### Python Implementation


In [15]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr.dtype)
float_arr=arr.astype(float)
print(float_arr)
print(float_arr.dtype)

int32
[10. 20. 30. 40.]
float64


## 9. Indexing

### Definition
Indexing accesses a specific array element using its position.

### Real-Life Example
We can retrieve the temperature recorded on a particular day.

### AI/ML Example
In AI/ML, indexing can access a particular sample, feature, or individual value from a dataset. For example, we can retrieve the first training sample using its index. This makes specific data easy to inspect or modify.

### Explanation
NumPy indexing starts from position 0, similar to Python lists. Positive indexes access elements from the beginning, while negative indexes can access elements from the end. Indexing also works with multidimensional arrays.

### Python Implementation


In [17]:
import numpy as np
arr=np.array([15,25,35,45,55])
print(arr[0])
print(arr[2])

15
35


## 10. Slicing

### Definition
Slicing selects a range or subset of elements from an array.

### Real-Life Example
From weekly sales, we can select only the first three days.

### AI/ML Example
In AI/ML, slicing can select particular rows, columns, samples, or features from a dataset. For example, we can separate selected features before model training. It is also useful for creating smaller subsets of data.

### Explanation
Slicing selects multiple elements without manually accessing each one. The common format is start:stop:step, and the stop position is not included. It works with both one-dimensional and multidimensional arrays.

### Python Implementation


In [19]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

[20 30 40]
[10 20 30]
[10 30 50]


## 11. Reshaping

### Definition
Reshaping changes an array's dimensions without changing its data.

### Real-Life Example
Six values can be rearranged into 2 rows and 3 columns.

### AI/ML Example
In AI/ML, reshaping is often required to match the input format expected by a model. For example, a flat set of values may need to become rows and columns. Deep-learning models also commonly require specific input shapes.

### Explanation
Reshaping changes the structure of an array while keeping the same data. The total number of elements must remain compatible with the new shape. NumPy provides reshape() for this operation.

### Python Implementation


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
new=arr.reshape(2,3)
print(new)
print(new.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## 12. Flatten

### Definition
Flatten converts a multidimensional array into a one-dimensional array.

### Real-Life Example
A table of marks can be converted into one continuous list.

### AI/ML Example
In AI/ML, flattening can convert multidimensional data into a single vector when required by a model. For example, image pixel values can be converted from rows and columns into one sequence. This is useful before some fully connected model inputs.

### Explanation
flatten() converts a multidimensional array into one dimension. It returns a new independent copy of the data. Changes to the flattened copy therefore do not change the original array.

### Python Implementation


In [23]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr.flatten())

[10 20 30 40 50 60]


## 13. Copy vs View

### Definition
A copy has independent data, while a view shares data with the original array.

### Real-Life Example
A photocopy can be changed independently, while a view refers to the same underlying information.

### AI/ML Example
In AI/ML preprocessing, understanding copy and view helps prevent accidental changes to the original dataset. A copy is useful when we want to modify data independently. A view is useful when we intentionally want to work with shared underlying data.

### Explanation
A copy creates separate data, so changing it does not affect the original array. A view shares the original array's data, so some changes can affect both. This distinction is important when manipulating datasets.

### Python Implementation


In [25]:
import numpy as np
arr=np.array([10,20,30,40])
c=arr.copy()
v=arr.view()
c[0]=100
v[1]=200
print('Original:',arr)
print('Copy:',c)
print('View:',v)

Original: [ 10 200  30  40]
Copy: [100  20  30  40]
View: [ 10 200  30  40]


## 14. Broadcasting

### Definition
Broadcasting lets NumPy perform operations on arrays with different but compatible shapes.

### Real-Life Example
If every product price increases by 50, we can add 50 to all prices at once.

### AI/ML Example
In AI/ML, broadcasting is used when applying the same mathematical operation across many samples or features. For example, a value can be added to every element of a feature array. It avoids manually repeating the value for each element.

### Explanation
Broadcasting allows NumPy to operate on arrays with different but compatible shapes. NumPy automatically expands the smaller value or dimension during the calculation. This makes array calculations shorter and efficient.

### Python Implementation


In [27]:
import numpy as np
prices=np.array([100,200,300,400])
print(prices+50)

[150 250 350 450]


## 15. Array Operations

### Definition
Array operations perform calculations such as addition, subtraction, multiplication, and division on arrays.

### Real-Life Example
A price increase can be applied to all product prices together.

### AI/ML Example
In AI/ML, array operations are used for feature transformations, matrix calculations, and model computations. Multiple values can be added, subtracted, multiplied, or divided at the same time. This is common during preprocessing and numerical model calculations.

### Explanation
NumPy supports fast element-wise arithmetic on compatible arrays. This means the operation is applied to corresponding elements automatically. It reduces the need for manual loops.

### Python Implementation


In [29]:
import numpy as np
a=np.array([10,20,30])
b=np.array([2,4,5])
print('Addition:',a+b)
print('Subtraction:',a-b)
print('Multiplication:',a*b)
print('Division:',a/b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


## 16. Universal Functions (ufuncs)

### Definition
Universal functions, or ufuncs, are NumPy functions that perform fast element-wise operations on arrays.

### Real-Life Example
We can calculate square roots of several values at the same time.

### AI/ML Example
In AI/ML, ufuncs can apply mathematical transformations to every value in numerical data. Functions such as logarithm, square root, and exponential are useful during preprocessing and mathematical calculations. They work efficiently across entire arrays.

### Explanation
Universal functions perform fast element-wise operations on NumPy arrays. Examples include np.sqrt(), np.exp(), np.log(), and np.absolute(). They make common mathematical transformations easy to apply.

### Python Implementation


In [31]:
import numpy as np
data=np.array([1,4,9,16,25])
print('Square Root:',np.sqrt(data))
print('Absolute:',np.absolute([-5,-2,3,7]))

Square Root: [1. 2. 3. 4. 5.]
Absolute: [5 2 3 7]
