# Notebook 2 – NumPy Mathematical Operations


In [1]:
import numpy as np


## 1. Sum

### Definition
Sum is the total obtained by adding all values in a NumPy array.

### Real-Life Example
Daily sales can be added to find total sales.

### AI/ML Example
In AI/ML, sum is used to total feature values, errors, probabilities, and other numerical results. It is commonly used during data analysis and loss calculations.

### Explanation
np.sum() adds array values quickly. It can calculate the total of an entire array or values along a selected axis.

### Python Implementation


In [3]:
arr=np.array([10,20,30,40])
print('Sum:',np.sum(arr))

Sum: 100


## 2. Mean

### Definition
Mean is the average value of the elements in an array.

### Real-Life Example
Student marks can be averaged to find the class average.

### AI/ML Example
In AI/ML, mean is used during data preprocessing and statistical analysis. It can also help fill missing numerical values and describe the center of a feature.

### Explanation
np.mean() calculates the arithmetic average. It adds all values and divides the result by the number of values.

### Python Implementation


In [5]:
arr=np.array([60,70,80,90,100])
print('Mean:',np.mean(arr))

Mean: 80.0


## 3. Median

### Definition
Median is the middle value of sorted data.

### Real-Life Example
Median house price gives a central value that is less affected by extreme prices.

### AI/ML Example
In AI/ML, median is useful when data contains outliers or is skewed. It is often used to fill missing numerical values in such features.

### Explanation
np.median() finds the middle value. If there are two middle values, NumPy returns their average.

### Python Implementation


In [7]:
arr=np.array([10,15,20,25,100])
print('Median:',np.median(arr))

Median: 20.0


## 4. Variance

### Definition
Variance measures how far values are spread from their mean.

### Real-Life Example
Marks that differ greatly from one another have higher variance.

### AI/ML Example
In AI/ML, variance helps understand how much a numerical feature changes. It is useful for analyzing feature spread and variability in a dataset.

### Explanation
np.var() calculates variance. Small variance means values are closer to the mean, while larger variance means they are more spread out.

### Python Implementation


In [9]:
arr=np.array([10,12,14,16,18])
print('Variance:',np.var(arr))

Variance: 8.0


## 5. Standard Deviation

### Definition
Standard deviation measures how much values typically differ from the mean.

### Real-Life Example
If exam marks are close to the average, standard deviation is small; if widely spread, it is larger.

### AI/ML Example
In AI/ML, standard deviation is important in data analysis and feature scaling. Standardization uses the mean and standard deviation to place features on a comparable scale.

### Explanation
np.std() calculates standard deviation. It is the square root of variance and is expressed in the same unit as the original data.

### Python Implementation


In [11]:
arr=np.array([10,12,14,16,18])
print('Standard Deviation:',np.std(arr))

Standard Deviation: 2.8284271247461903


## 6. Minimum

### Definition
Minimum is the smallest value in an array.

### Real-Life Example
From weekly temperatures, minimum gives the lowest recorded temperature.

### AI/ML Example
In AI/ML, minimum helps inspect the lower range of feature values. It is useful during exploratory analysis, normalization, and data validation.

### Explanation
np.min() returns the smallest value. It can also calculate minimum values along rows or columns.

### Python Implementation


In [13]:
arr=np.array([45,12,78,30,25])
print('Minimum:',np.min(arr))

Minimum: 12


## 7. Maximum

### Definition
Maximum is the largest value in an array.

### Real-Life Example
From monthly sales, maximum gives the highest sales amount.

### AI/ML Example
In AI/ML, maximum helps inspect the upper range of feature values. It is useful for checking ranges, unusual values, and normalization.

### Explanation
np.max() returns the largest value. It can work on an entire array or along a selected axis.

### Python Implementation


In [15]:
arr=np.array([45,12,78,30,25])
print('Maximum:',np.max(arr))

Maximum: 78


## 8. Argmin

### Definition
Argmin returns the index position of the smallest value in an array.

### Real-Life Example
For daily temperatures, argmin tells which position contains the lowest temperature.

### AI/ML Example
In AI/ML, argmin can identify the position of the smallest loss, distance, or score. For example, it can help choose the nearest cluster center using minimum distance.

### Explanation
np.argmin() returns an index, not the minimum value itself. That index can then be used to access the corresponding element.

### Python Implementation


In [17]:
arr=np.array([40,15,70,10,50])
i=np.argmin(arr)
print('Index:',i)
print('Value:',arr[i])

Index: 3
Value: 10


## 9. Argmax

### Definition
Argmax returns the index position of the largest value in an array.

### Real-Life Example
For player scores, argmax identifies the position of the highest score.

### AI/ML Example
In classification models, argmax is commonly used to select the class with the highest predicted probability. The returned index can represent the predicted class.

### Explanation
np.argmax() returns the index of the maximum value rather than the value itself. This is useful when the position represents a category or result.

### Python Implementation


In [29]:
p=np.array([0.10,0.25,0.65])
print('Predicted Class Index:',np.argmax(p))

Predicted Class Index: 2


## 10. Percentile

### Definition
A percentile gives the value below which a given percentage of observations fall.

### Real-Life Example
The 90th percentile of exam marks shows the score below which about 90% of marks fall.

### AI/ML Example
In AI/ML, percentiles help understand data distribution and identify extreme values. They can also be used to set thresholds during preprocessing.

### Explanation
np.percentile() calculates a requested percentile. Common values such as 25, 50, and 75 describe important positions in a distribution.

### Python Implementation


In [19]:
arr=np.array([10,20,30,40,50,60,70,80])
print('25th:',np.percentile(arr,25))
print('50th:',np.percentile(arr,50))
print('75th:',np.percentile(arr,75))

25th: 27.5
50th: 45.0
75th: 62.5


## 11. Dot Product

### Definition
Dot product multiplies corresponding elements of two vectors and adds the products.

### Real-Life Example
Quantity and price vectors can be combined to calculate a total value.

### AI/ML Example
In AI/ML, dot products are fundamental to linear models and neural networks. Input features are multiplied by model weights and combined to produce a weighted result.

### Explanation
np.dot() performs the dot product. For two 1D arrays, corresponding elements are multiplied and all products are added.

### Python Implementation


In [21]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print('Dot Product:',np.dot(a,b))

Dot Product: 32


## 12. Matrix Multiplication

### Definition
Matrix multiplication combines rows of the first matrix with columns of the second matrix.

### Real-Life Example
Several product quantities and prices can be combined using matrix calculations.

### AI/ML Example
In AI/ML, matrix multiplication is heavily used in neural networks, linear regression, and other models. It allows many inputs and weights to be processed together efficiently.

### Explanation
NumPy supports matrix multiplication using np.matmul() or the @ operator. The inner dimensions of the matrices must be compatible.

### Python Implementation


In [23]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A @ B)

[[19 22]
 [43 50]]


## 13. Transpose

### Definition
Transpose changes matrix rows into columns and columns into rows.

### Real-Life Example
A student-by-subject table can be transposed so subjects become rows.

### AI/ML Example
In AI/ML, transpose changes the orientation of datasets, vectors, and matrices. It is often required to make dimensions compatible for matrix calculations.

### Explanation
The .T attribute or np.transpose() can transpose an array. For a 2D matrix, rows and columns are exchanged.

### Python Implementation


In [25]:
A=np.array([[1,2,3],[4,5,6]])
print('Original:\n',A)
print('Transpose:\n',A.T)

Original:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


## 14. Basic Linear Algebra Operations

### Definition
Linear algebra operations work with vectors and matrices, including solving equations, determinants, inverses, and eigenvalues.

### Real-Life Example
Multiple equations containing unknown values can be solved together using linear algebra.

### AI/ML Example
Linear algebra is a foundation of AI/ML because data and model parameters are often represented as vectors and matrices. Regression, PCA, neural networks, and many algorithms depend on these operations.

### Explanation
NumPy provides np.linalg for linear algebra. Common functions include np.linalg.det(), np.linalg.inv(), np.linalg.solve(), and np.linalg.eig().

### Python Implementation


In [27]:
A=np.array([[2,1],[1,3]])
b=np.array([5,6])
print('Determinant:',np.linalg.det(A))
print('Inverse:\n',np.linalg.inv(A))
print('Solution:',np.linalg.solve(A,b))

Determinant: 5.000000000000001
Inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
Solution: [1.8 1.4]
